baseURL = "https://koda-project.github.io/KoDaWebSite/"
defaultContentLanguage  = "en"

title = "KoDa"

# Theme is loaded through a git submodule
theme = "trafiklab-2021"

enableEmoji = true
enableGitInfo = true

# paths
[permalinks]
  "/" = "/:title/"
  posts = "/:section/:title/"

# Multilingual
[languages]
  [languages.en]
  languageName = "English"
  weight = 2

# HTML for shortcodes
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  repository = "https://github.com/KoDa-project/KoDaWebSite/"